package handlers

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	"discord-bot/config"
	"discord-bot/payments"
	"discord-bot/storage"

	"github.com/bwmarrin/discordgo"
)

// stripeCurrencies is the full list of ISO 4217 currency codes supported by Stripe,
// paired with a human-readable label for the autocomplete menu.
var stripeCurrencies = [][2]string{
	{"USD", "USD — US Dollar"},
	{"EUR", "EUR — Euro"},
	{"GBP", "GBP — British Pound"},
	{"CAD", "CAD — Canadian Dollar"},
	{"AUD", "AUD — Australian Dollar"},
	{"CHF", "CHF — Swiss Franc"},
	{"JPY", "JPY — Japanese Yen"},
	{"NZD", "NZD — New Zealand Dollar"},
	{"SEK", "SEK — Swedish Krona"},
	{"NOK", "NOK — Norwegian Krone"},
	{"DKK", "DKK — Danish Krone"},
	{"HKD", "HKD — Hong Kong Dollar"},
	{"SGD", "SGD — Singapore Dollar"},
	{"MXN", "MXN — Mexican Peso"},
	{"BRL", "BRL — Brazilian Real"},
	{"INR", "INR — Indian Rupee"},
	{"PLN", "PLN — Polish Zloty"},
	{"CZK", "CZK — Czech Koruna"},
	{"HUF", "HUF — Hungarian Forint"},
	{"RON", "RON — Romanian Leu"},
	{"BGN", "BGN — Bulgarian Lev"},
	{"HRK", "HRK — Croatian Kuna"},
	{"ISK", "ISK — Icelandic Krona"},
	{"TRY", "TRY — Turkish Lira"},
	{"RUB", "RUB — Russian Ruble"},
	{"ZAR", "ZAR — South African Rand"},
	{"AED", "AED — UAE Dirham"},
	{"SAR", "SAR — Saudi Riyal"},
	{"QAR", "QAR — Qatari Riyal"},
	{"KWD", "KWD — Kuwaiti Dinar"},
	{"BHD", "BHD — Bahraini Dinar"},
	{"OMR", "OMR — Omani Rial"},
	{"ILS", "ILS — Israeli Shekel"},
	{"EGP", "EGP — Egyptian Pound"},
	{"MAD", "MAD — Moroccan Dirham"},
	{"KES", "KES — Kenyan Shilling"},
	{"NGN", "NGN — Nigerian Naira"},
	{"GHS", "GHS — Ghanaian Cedi"},
	{"TZS", "TZS — Tanzanian Shilling"},
	{"UGX", "UGX — Ugandan Shilling"},
	{"KRW", "KRW — South Korean Won"},
	{"CNY", "CNY — Chinese Yuan"},
	{"TWD", "TWD — Taiwan Dollar"},
	{"THB", "THB — Thai Baht"},
	{"MYR", "MYR — Malaysian Ringgit"},
	{"IDR", "IDR — Indonesian Rupiah"},
	{"PHP", "PHP — Philippine Peso"},
	{"VND", "VND — Vietnamese Dong"},
	{"PKR", "PKR — Pakistani Rupee"},
	{"BDT", "BDT — Bangladeshi Taka"},
	{"LKR", "LKR — Sri Lankan Rupee"},
	{"NPR", "NPR — Nepalese Rupee"},
	{"CLP", "CLP — Chilean Peso"},
	{"COP", "COP — Colombian Peso"},
	{"PEN", "PEN — Peruvian Sol"},
	{"ARS", "ARS — Argentine Peso"},
	{"UYU", "UYU — Uruguayan Peso"},
	{"BOB", "BOB — Bolivian Boliviano"},
	{"PYG", "PYG — Paraguayan Guarani"},
	{"GTQ", "GTQ — Guatemalan Quetzal"},
	{"CRC", "CRC — Costa Rican Colon"},
	{"HNL", "HNL — Honduran Lempira"},
	{"NIO", "NIO — Nicaraguan Córdoba"},
	{"DOP", "DOP — Dominican Peso"},
	{"JMD", "JMD — Jamaican Dollar"},
	{"TTD", "TTD — Trinidad Dollar"},
	{"BBD", "BBD — Barbadian Dollar"},
	{"XCD", "XCD — East Caribbean Dollar"},
	{"AWG", "AWG — Aruban Florin"},
	{"ANG", "ANG — Netherlands Antillean Guilder"},
	{"BMD", "BMD — Bermudian Dollar"},
	{"KYD", "KYD — Cayman Islands Dollar"},
	{"FJD", "FJD — Fijian Dollar"},
	{"PGK", "PGK — Papua New Guinean Kina"},
	{"WST", "WST — Samoan Tala"},
	{"TOP", "TOP — Tongan Pa'anga"},
	{"SBD", "SBD — Solomon Islands Dollar"},
	{"VUV", "VUV — Vanuatu Vatu"},
	{"XPF", "XPF — CFP Franc"},
	{"XOF", "XOF — West African CFA Franc"},